@baseUri = http://127.0.0.1:3003/api 

POST {{baseUri}}/sandbox
Content-Type: application/json

{
    "artifact": {
      "code": "#title"
    }
}

POST {{baseUri}}/chat
Content-Type: application/json

{
    "messages": [{
      "role": "user",
      "content": [{ "type": "text", "text": "introduce slidev" }]
    }]
}

POST {{baseUri}}/convertd

{
    "artifact": {
     "code": "#title"
    }
}

