import React from 'react';
import {
  FacebookShareButton,
  LinkedinShareButton,
  RedditShareButton,
  TelegramShareButton,
  TwitterShareButton,
} from "react-share";
import {BsX, BsFacebook, BsReddit, BsLinkedin, BsTelegram} from 'react-icons/bs'
import { toast } from 'react-toastify';
import { Button } from './ui/button';
import { Input } from './ui/input';

const Title = `Just published a presentation generated by @alexu19049062 to the community.
#RevealJS  #AI #createdwithai `
const Host = 'https://ppt.revealjs-ai.online'

export function ShareLink({url}: {url?: string}) {

  if (!url) {
    return
  }
  function copy(url: string) {
    navigator.clipboard.writeText(`${Host}${url}`)
      .then(() => {
        toast('Copied to clipboard')
      })
      .catch(err => {
        toast.error('Failed to copy: ' + url)
      })
  }
  return (
    <div className=" text-white rounded-lg mx-auto">
      <div className="flex mb-6">
        <div className="flex flex-col gap-4 justify-start">
          <div className='flex flex-row gap-2 items-center justify-start'>
            <h3 className="text-sm font-semibold mr3 w-[100px]">By Link: </h3>
            <Input
                type="text"
                value={url}
                readOnly
                className="flex-grow bg-gray-800 rounded-l-md px-3 py-2 text-sm"
              />
              <Button variant="secondary" onClick={() => copy(url)}>
                Copy Link
              </Button>
          </div>
          
          <div className="flex flex-row gap-2 items-center justify-start">
            <h3 className="text-sm font-semibold mr3">Share To:</h3>
            <div className="flex space-x-4">
                <TwitterShareButton url={url} title={Title}>
                  <BsX color="gray" size={24} />
                </TwitterShareButton>
                <FacebookShareButton url={url} title={Title}>
                  <BsFacebook color="gray" size={24}/>
                </FacebookShareButton>
                <LinkedinShareButton url={url} title={Title}>
                  <BsLinkedin color="gray" size={24} />
                </LinkedinShareButton>
                <RedditShareButton url={url} title={Title}>
                  <BsReddit size={24} color="gray"/>
                </RedditShareButton>
                <TelegramShareButton url={url} title={Title}>
                  <BsTelegram size={24} color="gray"/>
                </TelegramShareButton>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

